### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by maheshg77** [EMCECS/ecs-object-client-java#105]
The current version is primarily targeted for Java 8. We have apps that are on Java 17 / Spring Boot 3.1.x. There are conflicts with the versions of dependent jars with the version 3.4.5. Would there be a newer version made available which is Java 17 compatible.

**Comment by syuyangok** [comment]
We had a similar issue when upgrade to springboot 3.1.x:

2023-11-07T15:21:26.665Z [ecsHealth-0    ] ERROR c.g.v.o.c.e.EcsClient               : listObjects(health, heartbeat/) FAILED for host=ecss3-epg.dev.gm.com
javax.ws.rs.WebApplicationException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.readFrom(AbstractRootElementProvider.java:115)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.emc.object.s3.jersey.S3JerseyClient.executeRequest(S3JerseyClient.java:806)
	at com.emc.object.s3.jersey.S3JerseyClient.listObjects(S3JerseyClient.java:496)
	

Since springboot 3 use jakarta replace of javax, does ecs support for jakarta ?

**Comment by dunedodo** [comment]
> The current version is primarily targeted for Java 8. We have apps that are on Java 17 / Spring Boot 3.1.x. There are conflicts with the versions of dependent jars with the version 3.4.5. Would there be a newer version made available which is Java 17 compatible.

Yes, we will have some release compatible with OpenJDK 17.0.9 after finishing testing soon.

**Comment by dunedodo** [comment]
FYI., OpenJDK 17 will not be supported until ECS officially supports Java 17. If your request remains, just let me know. I can keep the ticket open, and also I would update here if ECS has any updates on the progress.

**Comment by SpiritWhite66** [comment]
Hi, I'm also interested in jdk 17 support.
