### ISSUE TITLE
Missing required header for this request: Content-MD5

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/ecs-object-client-java#13]
I'm getting the following error when I try to configure the bucket lifecycle.

```
Exception in thread "main" com.emc.object.s3.S3Exception: Missing required header for this request: Content-MD5
	at com.emc.object.s3.jersey.ErrorFilter.parseErrorResponse(ErrorFilter.java:136)
	at com.emc.object.s3.jersey.ErrorFilter.handle(ErrorFilter.java:70)
	at com.emc.object.s3.jersey.RetryFilter.handle(RetryFilter.java:65)
	at com.emc.object.s3.jersey.ChecksumFilter.handle(ChecksumFilter.java:50)
	at com.emc.object.s3.jersey.AuthorizationFilter.handle(AuthorizationFilter.java:79)
	at com.emc.object.s3.jersey.BucketFilter.handle(BucketFilter.java:80)
	at com.emc.object.s3.jersey.NamespaceFilter.handle(NamespaceFilter.java:78)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.method(WebResource.java:634)
	at com.emc.object.AbstractJerseyClient.executeRequest(AbstractJerseyClient.java:98)
	at com.emc.object.AbstractJerseyClient.executeAndClose(AbstractJerseyClient.java:54)
	at com.emc.object.s3.jersey.S3JerseyClient.setBucketLifecycle(S3JerseyClient.java:376)
	at com.emc.ecs.s3.sample._17_BucketLifecycle.main(_17_BucketLifecycle.java:39)
```

**Object client version:** 3.0.3
**ECS backend:** ECS Test Drive (3.1.0.0.95266.ab2753a)
**Code to reproduce the error:**
```
S3Client s3 = ECSS3Factory.getS3Client();
LifecycleRule rule = new LifecycleRule("rule-a", "abc", LifecycleRule.Status.Enabled, 1);
LifecycleConfiguration lc = new LifecycleConfiguration()
    .withRules(rule);
s3.setBucketLifecycle("bucket-a", lc);
```

**Comment by twincitiesguy** [comment]
Resolved in 3.0.4
