### ISSUE TITLE
Issue in updating the meta-data using setObjectMetadata method

### ISSUE THREAD

**Issue by meetniyazi** [EMCECS/ecs-object-client-java#73]
Hi , 

I am trying to update the existing meta data of the file , using "setObjectMetadata" by passing required input.
But while execution of the method receive the following error.

"
Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.emc.object.s3.bean.AccessControlList, and Java type class com.emc.object.s3.bean.AccessControlList, and MIME media type text/plain;charset=utf-8 was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:630)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at com.emc.object.s3.jersey.S3JerseyClient.executeRequest(S3JerseyClient.java:735)
	at com.emc.object.s3.jersey.S3JerseyClient.getObjectAcl(S3JerseyClient.java:676)
	at com.emc.object.s3.jersey.S3JerseyClient.getObjectAcl(S3JerseyClient.java:671)
	at com.ing.fedupload.fileuploader.TestMain.main(TestMain.java:37)
"

**Comment by dunedodo** [comment]
> Hi ,
> 
> I am trying to update the existing meta data of the file , using "setObjectMetadata" by passing required input. But while execution of the method receive the following error.
> 
> " Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class com.emc.object.s3.bean.AccessControlList, and Java type class com.emc.object.s3.bean.AccessControlList, and MIME media type text/plain;charset=utf-8 was not found at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:630) at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586) at com.emc.object.s3.jersey.S3JerseyClient.executeRequest(S3JerseyClient.java:735) at com.emc.object.s3.jersey.S3JerseyClient.getObjectAcl(S3JerseyClient.java:676) at com.emc.object.s3.jersey.S3JerseyClient.getObjectAcl(S3JerseyClient.java:671) at com.ing.fedupload.fileuploader.TestMain.main(TestMain.java:37) "

Is it an occurring issue from your side?

**Comment by dunedodo** [comment]
Hi @meetniyazi As it has been long from your last updates, we are going to close the issue in weeks. Please do not hesitate to contact us if you have any detailed requirements.
