### ISSUE TITLE
3.4.1 upload breaking change

### ISSUE THREAD

**Issue by TomDeBacker** [EMCECS/ecs-object-client-java#90]
Not sure if this is actually a breaking change but.. 

Since upgrading from 3.4.0 to 3.4.1 following code throws an exception:

```
Caused by: java.util.concurrent.ExecutionException: com.emc.object.s3.S3Exception: You must provide the Content-Length HTTP header.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.emc.object.s3.LargeFileUploader.doByteRangeUpload(LargeFileUploader.java:519)
	... 38 common frames omitted
Caused by: com.emc.object.s3.S3Exception: You must provide the Content-Length HTTP header.
	at com.emc.object.s3.jersey.ErrorFilter.parseErrorResponse(ErrorFilter.java:134)
	at com.emc.object.s3.jersey.ErrorFilter.handle(ErrorFilter.java:69)
	at com.emc.object.s3.jersey.RetryFilter.handle(RetryFilter.java:65)
	at com.emc.object.s3.jersey.ChecksumFilter.handle(ChecksumFilter.java:73)
	at com.emc.object.s3.jersey.AuthorizationFilter.handle(AuthorizationFilter.java:72)
	at com.emc.object.s3.jersey.BucketFilter.handle(BucketFilter.java:80)
	at com.emc.object.s3.jersey.NamespaceFilter.handle(NamespaceFilter.java:78)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.method(WebResource.java:634)
	at com.emc.object.AbstractJerseyClient.executeRequest(AbstractJerseyClient.java:98)
	at com.emc.object.AbstractJerseyClient.executeAndClose(AbstractJerseyClient.java:54)
	at com.emc.object.s3.jersey.S3JerseyClient.putObject(S3JerseyClient.java:554)
	at com.emc.object.s3.LargeFileUploader$PutObjectTask.call(LargeFileUploader.java:880)
	at com.emc.object.s3.LargeFileUploader$PutObjectTask.call(LargeFileUploader.java:864)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
@Override
    public void upload(String key, InputStream inputStream, long size) {
        LargeFileUploader fileUploader = new LargeFileUploader(this.client, bucket, key, inputStream, size);
        fileUploader.setObjectMetadata(new S3ObjectMetadata().withContentLength(size));
        fileUploader.doByteRangeUpload();
    }
```

Any idea what the issue is here. I see the Content-Length being set to zero in both versions in LargeFileUploader.configure(). Haven't been able yet to identify the difference between the versions.

Is our usage of uploading correct? What am I missing?

**Comment by TomDeBacker** [comment]
automagically fixed itself..
