### ISSUE TITLE
Internal Server Error in ECS Query Request

### ISSUE THREAD

**Issue by ShylajaL26** [EMCECS/ecs-object-client-java#97]
Getting below exception when i execute user metadata search query in ECS. Below is my code and sample query.
I am NOT getting this issue always. very rarely i am getting below exception. I am not able to find when this issue occurs  

Code:
QueryObjectsRequest queryObjectsRequest = new QueryObjectsRequest("bucketname.test")
				.withQuery(query);
		queryObjectsResult = s3JerseyClient.queryObjects(queryObjectsRequest);

Sample query:
(x-amz-meta-field1=='8') and (x-amz-meta-field2=='aa') and (x-amz-meta-field3=='bb')

Exception:
com.emc.object.s3.S3Exception: We encountered an internal error. Please try again.
	at com.emc.object.s3.jersey.ErrorFilter.parseErrorResponse(ErrorFilter.java:134)
	at com.emc.object.s3.jersey.ErrorFilter.handle(ErrorFilter.java:69)
	at com.emc.object.s3.jersey.RetryFilter.handle(RetryFilter.java:65)
	at com.emc.object.s3.jersey.ChecksumFilter.handle(ChecksumFilter.java:73)
	at com.emc.object.s3.jersey.AuthorizationFilter.handle(AuthorizationFilter.java:72)
	at com.emc.object.s3.jersey.BucketFilter.handle(BucketFilter.java:80)
	at com.emc.object.s3.jersey.NamespaceFilter.handle(NamespaceFilter.java:78)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.method(WebResource.java:623)
	at com.emc.object.AbstractJerseyClient.executeRequest(AbstractJerseyClient.java:107)
	at com.emc.object.s3.jersey.S3JerseyClient.executeRequest(S3JerseyClient.java:804)
	at com.emc.object.s3.jersey.S3JerseyClient.queryObjects(S3JerseyClient.java:465)

**Comment by dunedodo** [comment]
As there is no more updates since Dec 2022, this issue is closed. please refer to the advice above if you are still facing this problem.
